export type Locale = "zh" | "en";

export const siteCopy = {
  zh: {
    seo: {
      title: "风雨｜FDE · AI 产品落地与系统交付",
      description:
        "风雨，前沿部署工程师。帮助团队判断值得做的 AI 场景，完成原型验证、系统集成与生产上线，把业务问题变成可运行的产品。",
    },
    preferences: {
      group: "语言与主题设置",
      switchToEnglish: "Switch to English",
      switchToChinese: "切换为中文",
      switchToLight: "切换至日间模式",
      switchToDark: "切换至夜间模式",
      changedToEnglish: "Language changed to English",
      changedToChinese: "语言已切换为中文",
    },
    header: {
      home: "风雨首页",
      availability: "当前可承接 AI 落地项目",
      navLabel: "主导航",
      services: "服务",
      partners: "合作",
      caseStudy: "项目案例",
      process: "合作方式",
      about: "关于",
      contact: "聊聊合作",
      contactShort: "合作",
    },
    hero: {
      index: "发现 / 原型 / 部署 / 迭代 — 2026",
      kicker: "FORWARD DEPLOYED ENGINEER / 前沿部署工程师",
      kickerAside: "AI SOLUTIONS / PRODUCT / DELIVERY",
      title: [
        { text: "把业务难题，", outlined: false },
        { text: "变成可上线的", outlined: true },
        { text: "AI 产品。", outlined: false },
      ],
      label: "00 / INTRODUCTION",
      intro:
        "我是风雨，前沿部署工程师。你带来真实业务问题，我负责把需求、数据、模型与现有系统接起来——先验证价值，再稳定上线，避免项目停在 Demo。",
      cta: "聊聊你的 AI 场景",
      scroll: "向下探索",
    },
    ticker: {
      aria: "核心能力",
      items: ["场景诊断", "可用原型", "数据与系统集成", "生产上线", "运行优化"],
    },
    servicesSection: {
      label: "SERVICES",
      labelLocal: "服务能力",
      kicker: "FROM FIELD TO PRODUCTION",
      title: ["从一个真实问题开始，", "交付能跑起来的结果。"],
    },
    services: [
      {
        id: "discovery",
        number: "01",
        tag: "DISCOVERY & STRATEGY",
        title: "AI 场景诊断与路线设计",
        description:
          "适合知道 AI 值得尝试、却不确定先做什么的团队。先找出高价值切口，再决定是否投入开发。",
        items: ["业务流程与关键卡点", "场景优先级与风险判断", "分阶段方案与交付边界"],
      },
      {
        id: "prototype",
        number: "02",
        tag: "PROTOTYPE & VALIDATE",
        title: "可用原型与价值验证",
        description:
          "适合想降低试错成本的项目。在完整投入前，用真实数据和用户反馈验证效果、流程与采用意愿。",
        items: ["可操作的工作流或 Agent", "真实数据与工具接入", "效果评测与继续条件"],
      },
      {
        id: "delivery",
        number: "03",
        tag: "INTEGRATE & DEPLOY",
        title: "系统集成与生产上线",
        description:
          "适合已有 Demo、却卡在集成和上线的团队。把方案接入现有数据、权限与业务系统，做成可维护的产品。",
        items: ["全栈产品与关键链路", "企业系统、数据与模型接入", "测试、发布与运行监控"],
      },
      {
        id: "iteration",
        number: "04",
        tag: "ADOPT & ITERATE",
        title: "运行优化与团队交接",
        description:
          "适合已经上线、但使用效果不稳定的系统。围绕真实使用持续优化，并把关键能力交回团队。",
        items: ["使用反馈与问题复盘", "流程、体验与模型优化", "文档沉淀与能力交接"],
      },
    ],
    serviceAria: "了解并咨询",
    capabilitiesSection: {
      label: "CAPABILITIES",
      labelLocal: "核心能力",
      title: ["听得懂业务，", "也能把系统", "真正做完。"],
      intro:
        "你不必在咨询、产品和工程之间反复翻译。我会把业务目标拆成可验证方案，并沿着同一条责任链推进到上线与交接。",
    },
    capabilities: [
      { id: "field", number: "01", title: "把问题定义清楚", description: "进入真实流程，找到影响结果的关键卡点，而不是从模型能力倒推需求。" },
      { id: "prototype", number: "02", title: "让价值尽早可见", description: "快速做出能操作、能评测的原型，用证据决定继续、调整或停止。" },
      { id: "integration", number: "03", title: "打通关键业务链路", description: "连接前端、后端、数据、企业系统与模型，让方案融入现有工作。" },
      { id: "production", number: "04", title: "对上线结果负责", description: "补齐权限、评测、日志、发布和交接，让系统上线后仍然可控。" },
    ],
    partners: {
      label: "TRUST & COLLABORATION",
      labelLocal: "合作品牌",
      kicker: "DISCLOSED WITH PERMISSION",
      title: ["合作建立在交付，", "也建立在信任边界。"],
      intro:
        "这里只展示获得许可的合作信息。未公开的客户与项目默认保密，不用 Logo 数量制造信任——让真实案例和沟通质量证明合作价值。",
      aria: "已公开的合作品牌与项目",
      tiles: [
        {
          id: "wude",
          kind: "brand",
          eyebrow: "CONFIRMED COLLABORATION / 已确认协作",
          mark: "WUDE",
          name: "WUDE 项目团队",
          note: "已确认的工程项目协作",
        },
        {
          id: "disclosure",
          kind: "policy",
          eyebrow: "DISCLOSURE POLICY / 披露原则",
          mark: "默认保密",
          name: "客户名称、资料与业务数据",
          note: "只有获得明确许可才公开展示",
        },
        {
          id: "next",
          kind: "cta",
          eyebrow: "NEXT COLLABORATION / 下一次合作",
          mark: "YOUR TEAM",
          name: "带着一个具体难题来聊",
          note: "先判断价值、可行性与合作边界",
        },
      ],
    },
    caseStudy: {
      label: "SELECTED WORK",
      labelLocal: "项目实战",
      kicker: "AI APPLICATIONS / PLATFORM ENGINEERING",
      title: ["真实项目不只看界面，", "更要看它如何落地。"],
      intro:
        "每个案例都说明它解决什么问题、系统如何运行、关键工程难点在哪里，以及我在项目中的角色。用左右按钮切换，找到与你最接近的场景。",
      previous: "上一个案例",
      next: "下一个案例",
      keyboardHint: "聚焦案例后，可使用左右方向键切换；Home 和 End 跳到首尾案例。",
      imageLabel: "PROJECT MATERIAL / 项目资料",
      roleLabel: "MY ROLE / 我的角色",
      discuss: "聊聊我的类似需求",
      disclosure:
        "以下均为风雨主导的团队项目。页面只呈现获准公开的系统信息；团队成员、客户敏感资料与量化结果继续遵循保密与授权边界。",
      projects: [
        {
          id: "mental-health-platform",
          number: "CASE 01",
          year: "2026",
          category: "行业 SaaS / AI 应用",
          purpose: "心理服务数字化闭环",
          imageSrc: "/cases/mental-health-platform.png",
          imageAlt: "大白 AI 心理健康平台项目宣传图，展示 AI 咨询、组织心理画像、风险预警与快速筛查",
          imageWidth: 903,
          imageHeight: 502,
          imageNote: "已授权项目宣传图",
          title: "大白 AI 心理健康平台",
          summary:
            "把咨询、测评、风险预警与交易串成一套可持续服务闭环，让用户体验与运营状态在同一系统中推进。",
          flow: ["ASSESS", "CHAT", "SERVICE", "DELIVER"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "服务发现与网关 → 用户及会话状态 → SSE 流式 AI 对话 → 测评与报告 → 咨询、交易及支付 → 持续交付。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "让对话、测评、咨询和交易共享可追踪状态，并处理异步回调、超时、支付幂等、发布检查与回滚。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Spring Cloud / SSE / MongoDB / Payment / Vue 3 / CI/CD",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者，推动业务目标、工程方案与交付节奏对齐；敏感信息按授权范围披露。",
          tagsLabel: "大白 AI 项目技术标签",
          tags: ["AI CONSULTATION", "SSE", "TRANSACTION STATE", "CI/CD"],
        },
        {
          id: "industrial-compliance-platform",
          number: "CASE 02",
          year: "2025—2026",
          category: "私有 AI / RAG 平台",
          purpose: "私有知识检索与溯源",
          imageSrc: "/cases/industrial-compliance-platform.png",
          imageAlt: "工业合规知识平台界面截图，展示区域风险趋势、风险分布热力图与雷达图",
          imageWidth: 1859,
          imageHeight: 912,
          imageNote: "已授权项目界面截图",
          title: "工业合规知识平台",
          summary:
            "让分散且敏感的合规资料在内网中可搜索、可追溯、可更新，为一线判断提供有来源的答案。",
          flow: ["DOCS", "PARSE", "INDEX", "ANSWER"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "文档接入 → 解析、清洗与分块 → 异步向量化 → 混合检索与重排 → 本地模型生成 → 原文追溯。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "构建可重跑的文档流水线、可恢复的异步向量任务，以及内网模型部署、依赖降级和答案溯源能力。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Java 17 / RAG / Redis Stream / Vector Search / Local LLM / Kubernetes",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者，推动业务目标、工程方案与交付节奏对齐；敏感信息按授权范围披露。",
          tagsLabel: "工业合规项目技术标签",
          tags: ["PRIVATE AI", "HYBRID SEARCH", "LOCAL LLM", "KUBERNETES"],
        },
        {
          id: "sre-copilot",
          number: "CASE 03",
          year: "2025",
          category: "AI Agent / 可观测性",
          purpose: "可审计的智能故障诊断",
          imageSrc: "/cases/sre-copilot.png",
          imageAlt: "智能 SRE 运维助手界面截图，展示 Kubernetes 调查时间线、日志与支持证据",
          imageWidth: 1859,
          imageHeight: 903,
          imageNote: "已授权项目界面截图",
          title: "智能 SRE 运维助手",
          summary:
            "把指标、日志与集群事件串成可追踪的调查链路，帮助运维团队更快聚焦线索，同时保留人工判断与工具边界。",
          flow: ["OBSERVE", "REASON", "ACT", "REPORT"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "问题输入 → 调查计划 → 工具作用域校验 → 指标、日志与 Kubernetes 查询 → 流式证据 → 诊断总结。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "明确集群、命名空间与时间窗口边界，将计划和工具调用保存为可观察事件，并支持中断、执行上限与模型降级。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Spring Boot 3 / React / AI Agent / MCP / Prometheus / Kubernetes",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者，推动业务目标、工程方案与交付节奏对齐；敏感信息按授权范围披露。",
          tagsLabel: "SRE 助手项目技术标签",
          tags: ["AI AGENT", "MCP", "PROMETHEUS", "KUBERNETES"],
        },
        {
          id: "content-orchestration",
          number: "CASE 04",
          year: "2025—2026",
          category: "AIGC 基础设施 / 任务编排",
          purpose: "规模化内容生产调度",
          imageSrc: "/cases/content-orchestration-schematic.png",
          imageAlt: "生成式内容调度平台的任务接入、优先级队列、模型网关与实时进度链路示意图，非实机截图",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "本站调度链路示意图 · 非实机截图",
          title: "生成式内容调度平台",
          summary:
            "把分散的批量生成任务集中到统一工作台，统一输入、模型、队列与进度，降低规模化生产的操作复杂度。",
          flow: ["IMPORT", "QUEUE", "MODEL", "EXPORT"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "表格导入 → 模板变量与任务校验 → 分级队列 → 多模型网关 → 重试与状态流转 → WebSocket 进度 → 结果导出。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "统一输入校验和任务标准，管理优先级、队列积压与失败重试，隔离模型供应方差异并实时反馈进度。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "NestJS / TypeScript / Redis Stream / WebSocket / Vue 3 / Docker",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者，推动业务目标、工程方案与交付节奏对齐；敏感信息按授权范围披露。",
          tagsLabel: "生成式内容调度项目技术标签",
          tags: ["TASK QUEUE", "MODEL GATEWAY", "WEBSOCKET", "DOCKER"],
        },
      ],
    },
    process: {
      label: "PROCESS",
      labelLocal: "合作流程",
      kicker: "DISCOVER. PROTOTYPE. DEPLOY. ITERATE.",
      title: ["先用小成本验证，", "再把有效方案推到生产。"],
      steps: [
        { id: "discover", number: "01", tag: "DISCOVER", title: "对齐结果与边界", description: "明确要改善的业务结果、真实用户、可用数据和不可触碰的约束。" },
        { id: "prototype", number: "02", tag: "PROTOTYPE", title: "用原型消除最大风险", description: "先验证最关键的流程和效果，让继续、调整或停止都有依据。" },
        { id: "deploy", number: "03", tag: "DEPLOY", title: "接入现有系统上线", description: "补齐数据、权限、异常、测试与发布链路，把 Demo 变成可运行产品。" },
        { id: "iterate", number: "04", tag: "ITERATE", title: "用真实使用持续优化", description: "依据反馈改善流程、体验与模型，并完成文档和团队交接。" },
      ],
    },
    about: {
      label: "PHILOSOPHY",
      labelLocal: "我的理念",
      quote: "“不以 Demo 交差，让 AI 在真实业务里被用起来、跑得稳定。”",
      body: "我会先判断一个场景是否值得做，再选择足够简单、能够验证的方案。真正的交付不仅是代码，还包括业务采用、数据与权限边界、运行稳定性，以及团队接得住的长期维护方式。",
    },
    contact: {
      label: "CONTACT",
      labelLocal: "开始合作",
      status: "当前可承接 AI 落地合作",
      titleStart: "把你的业务问题，",
      titleEnd: "变成下一项上线成果。",
      body: "已有明确场景，可以带上当前卡点与期望结果；还不确定从哪里开始，也可以先描述业务流程。我会从价值、可行性和交付边界出发，给出下一步建议。",
      emailListLabel: "联系邮箱",
      emailAria: "发送合作邮件到",
      copyIdle: "复制合作沟通模板",
      copyWorking: "正在复制合作模板",
      copyDone: "合作模板已复制",
      copyFailed: "复制失败，请重试",
      copyCodeIdle: "COPY BRIEF",
      copyCodeWorking: "COPYING",
      copyCodeDone: "COPIED",
      copyCodeFailed: "RETRY",
      liveDone: "合作沟通模板已复制到剪贴板",
      liveFailed: "复制失败，请重试",
      mailSubject: "AI 落地项目合作｜业务场景初步沟通",
      mailTemplate: `你好风雨，我想沟通一个 AI 落地项目。\n\n业务场景与使用者：\n当前问题：\n已有数据或系统：\n期望结果：\n计划时间：\n预算范围（可选）：`,
    },
    footer: {
      tagline: "从真实问题出发，交付可运行的 AI。",
      backToTop: "返回顶部 ↑",
    },
  },
  en: {
    seo: {
      title: "Fengyu | FDE for AI Product Delivery",
      description:
        "Fengyu is a Forward Deployed Engineer helping teams identify AI use cases worth building, validate them with working prototypes, integrate systems, and ship reliable products.",
    },
    preferences: {
      group: "Language and theme settings",
      switchToEnglish: "Switch to English",
      switchToChinese: "切换为中文",
      switchToLight: "Switch to light mode",
      switchToDark: "Switch to dark mode",
      changedToEnglish: "Language changed to English",
      changedToChinese: "语言已切换为中文",
    },
    header: {
      home: "Fengyu home",
      availability: "Available for AI delivery projects",
      navLabel: "Primary navigation",
      services: "Services",
      partners: "Partners",
      caseStudy: "Case studies",
      process: "How we work",
      about: "About",
      contact: "Start a project",
      contactShort: "Talk",
    },
    hero: {
      index: "DISCOVER / PROTOTYPE / DEPLOY / ITERATE — 2026",
      kicker: "FORWARD DEPLOYED ENGINEER / FIELD TO PRODUCTION",
      kickerAside: "AI SOLUTIONS / PRODUCT / DELIVERY",
      title: [
        { text: "Turn real problems", outlined: false },
        { text: "into AI that ships", outlined: true },
        { text: "and keeps working.", outlined: false },
      ],
      label: "00 / INTRODUCTION",
      intro:
        "I’m Fengyu, a Forward Deployed Engineer. Bring the real workflow; I connect users, data, models and existing systems—validate value first, then ship with the controls production requires.",
      cta: "Discuss your AI use case",
      scroll: "Scroll to explore",
    },
    ticker: {
      aria: "Core capabilities",
      items: ["Use-case discovery", "Working prototypes", "Data and system integration", "Production launch", "Operational improvement"],
    },
    servicesSection: {
      label: "SERVICES",
      labelLocal: "What I deliver",
      kicker: "FROM FIELD TO PRODUCTION",
      title: ["Start with one real problem.", "Deliver something that works."],
    },
    services: [
      {
        id: "discovery",
        number: "01",
        tag: "DISCOVERY & STRATEGY",
        title: "AI use-case discovery & roadmap",
        description: "For teams that see AI potential but do not know what to build first. Find the highest-value entry point before committing to development.",
        items: ["Workflow and critical bottlenecks", "Use-case priority and risk assessment", "Phased roadmap and delivery boundaries"],
      },
      {
        id: "prototype",
        number: "02",
        tag: "PROTOTYPE & VALIDATE",
        title: "Working prototypes & value validation",
        description: "For projects that need to reduce uncertainty. Test the workflow, quality and adoption with real data before making the full investment.",
        items: ["Usable workflow or agent", "Real data and tool integration", "Evaluation and go-forward criteria"],
      },
      {
        id: "delivery",
        number: "03",
        tag: "INTEGRATE & DEPLOY",
        title: "System integration & production launch",
        description: "For teams with a demo stuck before launch. Connect the solution to existing data, permissions and business systems, then make it maintainable.",
        items: ["Full-stack product and critical paths", "Enterprise system, data and model integration", "Testing, release and operational monitoring"],
      },
      {
        id: "iteration",
        number: "04",
        tag: "ADOPT & ITERATE",
        title: "Operational improvement & handoff",
        description: "For systems already live but not yet reliable in use. Improve them around real feedback and transfer the capability back to the team.",
        items: ["Usage feedback and issue review", "Workflow, experience and model improvement", "Documentation and capability handoff"],
      },
    ],
    serviceAria: "Learn about and discuss",
    capabilitiesSection: {
      label: "CAPABILITIES",
      labelLocal: "How I contribute",
      title: ["Understands the business.", "Finishes the system.", "Owns the path to launch."],
      intro: "You should not have to translate between consultants, product and engineering. I turn the business goal into a testable plan and carry one responsibility chain through launch and handoff.",
    },
    capabilities: [
      { id: "field", number: "01", title: "Define the right problem", description: "Enter the real workflow and find the bottleneck that changes outcomes instead of forcing a model-first idea." },
      { id: "prototype", number: "02", title: "Make value visible early", description: "Build something usable and measurable, so the team has evidence to continue, adjust or stop." },
      { id: "integration", number: "03", title: "Connect the critical workflow", description: "Join frontend, backend, data, enterprise systems and models so the solution fits existing work." },
      { id: "production", number: "04", title: "Own the path to launch", description: "Cover permissions, evaluation, logs, release and handoff so the system remains controllable after launch." },
    ],
    partners: {
      label: "TRUST & COLLABORATION",
      labelLocal: "Collaboration and disclosure",
      kicker: "DISCLOSED WITH PERMISSION",
      title: ["Trust is built through delivery", "and clear boundaries."],
      intro: "Only collaboration information approved for disclosure appears here. Undisclosed clients and projects remain confidential; names and marks are added only with permission, never borrowed to manufacture trust.",
      aria: "Disclosed partners and projects",
      tiles: [
        { id: "wude", kind: "brand", eyebrow: "CONFIRMED COLLABORATION", mark: "WUDE", name: "WUDE project team", note: "Confirmed engineering project collaboration" },
        { id: "disclosure", kind: "policy", eyebrow: "DISCLOSURE POLICY", mark: "CONFIDENTIAL BY DEFAULT", name: "Client names, materials and business data", note: "Published only with explicit permission" },
        { id: "next", kind: "cta", eyebrow: "NEXT COLLABORATION", mark: "YOUR TEAM", name: "Bring one concrete problem", note: "Start with value, feasibility and delivery boundaries" },
      ],
    },
    caseStudy: {
      label: "SELECTED WORK",
      labelLocal: "Case studies",
      kicker: "AI APPLICATIONS / PLATFORM ENGINEERING",
      title: ["Real projects are more than screens.", "See how they reach production."],
      intro:
        "Each case explains the problem it solves, how the system works, where the engineering gets hard, and my role in delivery. Use the arrows to find the scenario closest to yours.",
      previous: "Previous case",
      next: "Next case",
      keyboardHint: "Focus the case and use Left or Right Arrow to switch; Home and End jump to the first or last case.",
      imageLabel: "PROJECT MATERIAL",
      roleLabel: "MY ROLE",
      discuss: "Discuss a similar need",
      disclosure:
        "These are team projects led by Fengyu. Only approved system information appears here; team details, client-sensitive material and measured outcomes remain within agreed confidentiality boundaries.",
      projects: [
        {
          id: "mental-health-platform",
          number: "CASE 01",
          year: "2026",
          category: "Industry SaaS / AI Application",
          purpose: "End-to-end mental health services",
          imageSrc: "/cases/mental-health-platform.png",
          imageAlt: "Dabai AI mental health platform project visual showing AI consultation, organizational wellbeing profiles, risk alerts and rapid screening",
          imageWidth: 903,
          imageHeight: 502,
          imageNote: "Authorized project promotional visual",
          title: "Dabai AI Mental Health Platform",
          summary:
            "Connect consultation, assessment, risk alerts and transactions in one service loop, keeping the user experience and operational state in the same system.",
          flow: ["ASSESS", "CHAT", "SERVICE", "DELIVER"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Service discovery and gateway → user and session state → SSE-based AI conversations → assessments and reports → consultation, transaction and payment → continuous delivery.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Traceable state across conversations, assessments, consultations and transactions, with asynchronous callbacks, timeout handling, payment idempotency, release checks and rollback readiness.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Spring Cloud / SSE / MongoDB / Payment / Vue 3 / CI/CD",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead, aligning business goals, engineering decisions and delivery cadence; sensitive details follow agreed disclosure boundaries.",
          tagsLabel: "Dabai AI project technology tags",
          tags: ["AI CONSULTATION", "SSE", "TRANSACTION STATE", "CI/CD"],
        },
        {
          id: "industrial-compliance-platform",
          number: "CASE 02",
          year: "2025–2026",
          category: "Private AI / RAG Platform",
          purpose: "Private knowledge retrieval and traceability",
          imageSrc: "/cases/industrial-compliance-platform.png",
          imageAlt: "Industrial compliance knowledge platform interface showing regional risk trends, a risk heat map and radar chart",
          imageWidth: 1859,
          imageHeight: 912,
          imageNote: "Authorized project interface capture",
          title: "Industrial Compliance Knowledge Platform",
          summary:
            "Make fragmented, sensitive compliance material searchable, traceable and maintainable inside the private environment, with source-backed answers for frontline decisions.",
          flow: ["DOCS", "PARSE", "INDEX", "ANSWER"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Document ingestion → parsing, cleaning and chunking → asynchronous embedding → hybrid retrieval and reranking → local-model generation → source traceability.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Re-runnable document pipelines, recoverable asynchronous embedding tasks, private model deployment, graceful degradation and source-backed answers.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Java 17 / RAG / Redis Stream / Vector Search / Local LLM / Kubernetes",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead, aligning business goals, engineering decisions and delivery cadence; sensitive details follow agreed disclosure boundaries.",
          tagsLabel: "Industrial compliance project technology tags",
          tags: ["PRIVATE AI", "HYBRID SEARCH", "LOCAL LLM", "KUBERNETES"],
        },
        {
          id: "sre-copilot",
          number: "CASE 03",
          year: "2025",
          category: "AI Agent / Observability",
          purpose: "Auditable incident diagnosis",
          imageSrc: "/cases/sre-copilot.png",
          imageAlt: "Intelligent SRE operations assistant interface showing a Kubernetes investigation timeline, logs and supporting evidence",
          imageWidth: 1859,
          imageHeight: 903,
          imageNote: "Authorized project interface capture",
          title: "Intelligent SRE Operations Assistant",
          summary:
            "Turn metrics, logs and cluster events into a traceable investigation flow that narrows the search faster while preserving human judgment and tool boundaries.",
          flow: ["OBSERVE", "REASON", "ACT", "REPORT"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "User question → investigation plan → tool-scope validation → metrics, logs and Kubernetes queries → streamed evidence → diagnostic summary.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Explicit cluster, namespace and time-window boundaries, observable tool events, interruption, execution limits and model fallback.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Spring Boot 3 / React / AI Agent / MCP / Prometheus / Kubernetes",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead, aligning business goals, engineering decisions and delivery cadence; sensitive details follow agreed disclosure boundaries.",
          tagsLabel: "SRE assistant project technology tags",
          tags: ["AI AGENT", "MCP", "PROMETHEUS", "KUBERNETES"],
        },
        {
          id: "content-orchestration",
          number: "CASE 04",
          year: "2025–2026",
          category: "AIGC Infrastructure / Orchestration",
          purpose: "Content production at scale",
          imageSrc: "/cases/content-orchestration-schematic.png",
          imageAlt: "Non-production schematic of task intake, priority queues, a model gateway and live progress for the generative content orchestration platform",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "On-site orchestration schematic · not a production screenshot",
          title: "Generative Content Orchestration Platform",
          summary:
            "Bring fragmented batch-generation work into one workspace, standardizing inputs, model access, queues and progress while reducing operational complexity at scale.",
          flow: ["IMPORT", "QUEUE", "MODEL", "EXPORT"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Spreadsheet import → template variables and validation → priority queues → multi-model gateway → retries and state transitions → WebSocket progress → export.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Standardized validation and task definitions, queue pressure and retry management, provider abstraction and real-time execution feedback.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "NestJS / TypeScript / Redis Stream / WebSocket / Vue 3 / Docker",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead, aligning business goals, engineering decisions and delivery cadence; sensitive details follow agreed disclosure boundaries.",
          tagsLabel: "Generative content orchestration technology tags",
          tags: ["TASK QUEUE", "MODEL GATEWAY", "WEBSOCKET", "DOCKER"],
        },
      ],
    },
    process: {
      label: "PROCESS",
      labelLocal: "How we work",
      kicker: "DISCOVER. PROTOTYPE. DEPLOY. ITERATE.",
      title: ["Validate with a smaller bet.", "Scale only what proves useful."],
      steps: [
        { id: "discover", number: "01", tag: "DISCOVER", title: "Align on outcomes and boundaries", description: "Define the result to improve, the real users, available data and constraints that cannot be crossed." },
        { id: "prototype", number: "02", tag: "PROTOTYPE", title: "Remove the biggest risk first", description: "Validate the critical workflow and quality so the team has evidence to continue, adjust or stop." },
        { id: "deploy", number: "03", tag: "DEPLOY", title: "Integrate with existing systems", description: "Complete data, permissions, failure handling, testing and release so the demo becomes an operating product." },
        { id: "iterate", number: "04", tag: "ITERATE", title: "Improve through real usage", description: "Use feedback to refine the workflow, experience and model, then complete documentation and handoff." },
      ],
    },
    about: {
      label: "PHILOSOPHY",
      labelLocal: "What I believe",
      quote: "“The goal is not a convincing demo. It is AI that gets used and keeps working.”",
      body: "I first ask whether a use case is worth building, then choose the simplest path that can prove it. Delivery includes more than code: adoption, data and permission boundaries, reliability, and a maintenance model the team can own.",
    },
    contact: {
      label: "CONTACT",
      labelLocal: "Start a project",
      status: "Available for AI delivery projects",
      titleStart: "Turn your business problem",
      titleEnd: "into the next shipped outcome.",
      body: "If you have a defined use case, bring the current blocker and desired result. If you do not know where to start, describe the workflow. I will respond around value, feasibility and clear delivery boundaries.",
      emailListLabel: "Contact email addresses",
      emailAria: "Send a project email to",
      copyIdle: "Copy the project brief",
      copyWorking: "Copying the project brief",
      copyDone: "Project brief copied",
      copyFailed: "Copy failed. Try again",
      copyCodeIdle: "COPY BRIEF",
      copyCodeWorking: "COPYING",
      copyCodeDone: "COPIED",
      copyCodeFailed: "RETRY",
      liveDone: "The project brief was copied to your clipboard",
      liveFailed: "Copy failed. Please try again",
      mailSubject: "AI delivery project | Initial use-case discussion",
      mailTemplate: `Hi Fengyu, I’d like to discuss an AI delivery project.\n\nBusiness context and users:\nCurrent problem:\nExisting data or systems:\nDesired outcome:\nTarget timeline:\nBudget range (optional):`,
    },
    footer: {
      tagline: "Start with a real problem. Deliver AI that works.",
      backToTop: "BACK TO TOP ↑",
    },
  },
} as const;
