export type Locale = "zh" | "en";

export const siteCopy = {
  zh: {
    seo: {
      title: "风雨｜FDE · AI 产品落地与系统交付",
      description:
        "风雨，前沿部署工程师。帮助团队判断值得做的 AI 场景，完成原型验证、系统集成与生产上线，把业务问题变成可运行的产品。",
    },
    preferences: {
      group: "语言与主题设置",
      switchToEnglish: "Switch to English",
      switchToChinese: "切换为中文",
      switchToLight: "切换至日间模式",
      switchToDark: "切换至夜间模式",
      changedToEnglish: "Language changed to English",
      changedToChinese: "语言已切换为中文",
    },
    header: {
      home: "风雨首页",
      availability: "当前可承接 AI 落地项目",
      navLabel: "主导航",
      services: "服务",
      partners: "合作",
      caseStudy: "项目案例",
      process: "合作方式",
      about: "关于",
      contact: "聊聊合作",
      contactShort: "合作",
    },
    hero: {
      index: "发现 / 原型 / 部署 / 迭代 — 2026",
      kicker: "FORWARD DEPLOYED ENGINEER / 前沿部署工程师",
      kickerAside: "AI SOLUTIONS / PRODUCT / DELIVERY",
      title: [
        { text: "把业务难题，", outlined: false },
        { text: "变成可上线的", outlined: true },
        { text: "AI 产品。", outlined: false },
      ],
      label: "00 / INTRODUCTION",
      intro:
        "我是风雨，前沿部署工程师。你带来真实业务问题，我负责把需求、数据、模型与现有系统接起来——先验证价值，再稳定上线，避免项目停在 Demo。",
      cta: "聊聊你的 AI 场景",
      scroll: "向下探索",
    },
    ticker: {
      aria: "核心能力",
      items: ["场景诊断", "可用原型", "数据与系统集成", "生产上线", "运行优化"],
    },
    servicesSection: {
      label: "SERVICES",
      labelLocal: "服务能力",
      kicker: "FROM FIELD TO PRODUCTION",
      title: ["从一个真实问题开始，", "交付能跑起来的结果。"],
    },
    services: [
      {
        id: "discovery",
        number: "01",
        tag: "DISCOVERY & STRATEGY",
        title: "AI 场景诊断与路线设计",
        description:
          "适合知道 AI 值得尝试、却不确定先做什么的团队。先找出高价值切口，再决定是否投入开发。",
        items: ["业务流程与关键卡点", "场景优先级与风险判断", "分阶段方案与交付边界"],
      },
      {
        id: "prototype",
        number: "02",
        tag: "PROTOTYPE & VALIDATE",
        title: "可用原型与价值验证",
        description:
          "适合想降低试错成本的项目。在完整投入前，用真实数据和用户反馈验证效果、流程与采用意愿。",
        items: ["可操作的工作流或 Agent", "真实数据与工具接入", "效果评测与继续条件"],
      },
      {
        id: "delivery",
        number: "03",
        tag: "INTEGRATE & DEPLOY",
        title: "系统集成与生产上线",
        description:
          "适合已有 Demo、却卡在集成和上线的团队。把方案接入现有数据、权限与业务系统，做成可维护的产品。",
        items: ["全栈产品与关键链路", "企业系统、数据与模型接入", "测试、发布与运行监控"],
      },
      {
        id: "iteration",
        number: "04",
        tag: "ADOPT & ITERATE",
        title: "运行优化与团队交接",
        description:
          "适合已经上线、但使用效果不稳定的系统。围绕真实使用持续优化，并把关键能力交回团队。",
        items: ["使用反馈与问题复盘", "流程、体验与模型优化", "文档沉淀与能力交接"],
      },
    ],
    serviceAria: "了解并咨询",
    capabilitiesSection: {
      label: "CAPABILITIES",
      labelLocal: "核心能力",
      title: ["听得懂业务，", "也能把系统", "真正做完。"],
      intro:
        "你不必在咨询、产品和工程之间反复翻译。我会把业务目标拆成可验证方案，并沿着同一条责任链推进到上线与交接。",
    },
    capabilities: [
      { id: "field", number: "01", title: "把问题定义清楚", description: "进入真实流程，找到影响结果的关键卡点，而不是从模型能力倒推需求。" },
      { id: "prototype", number: "02", title: "让价值尽早可见", description: "快速做出能操作、能评测的原型，用证据决定继续、调整或停止。" },
      { id: "integration", number: "03", title: "打通关键业务链路", description: "连接前端、后端、数据、企业系统与模型，让方案融入现有工作。" },
      { id: "production", number: "04", title: "对上线结果负责", description: "补齐权限、评测、日志、发布和交接，让系统上线后仍然可控。" },
    ],
    partners: {
      label: "TRUST & COLLABORATION",
      labelLocal: "合作品牌",
      kicker: "VERIFIED BRANDS / VISUAL PLACEHOLDERS",
      title: ["合作建立在交付，", "也建立在信任边界。"],
      intro:
        "滚动墙同时展示已确认并获得公开许可的部分合作与产品品牌，以及明确标注的纯视觉占位。视觉占位不对应任何具体客户、合作或公开品牌，也不构成品牌背书。当前并未完整展示全部合作记录；其余品牌、客户名称、项目资料与业务数据因保密约定不公开。",
      aria: "已公开品牌与纯视觉占位；视觉占位不代表客户、合作或品牌背书",
      pauseMotion: "暂停品牌滚动",
      tiles: [
        {
          id: "funeng-rare-earth",
          kind: "brand",
          eyebrow: "CONFIRMED COLLABORATION / 已确认合作",
          mark: "复能稀土",
          name: "宁波复能稀土新材料股份有限公司",
          note: "已确认并获准公开展示的合作品牌",
        },
        {
          id: "chenghui-tech",
          kind: "brand",
          eyebrow: "CONFIRMED COLLABORATION / 已确认合作",
          mark: "橙绘科技",
          name: "温州橙绘科技有限公司",
          note: "已确认并获准公开展示的合作品牌",
        },
        {
          id: "lynkvis-ai",
          kind: "brand",
          eyebrow: "PRODUCT DELIVERY / 产品交付",
          mark: "LYNKVIS AI",
          name: "Lynkvis AI",
          note: "室内设计 AI 产品研发与全栈交付",
          logoSrc: "/brands/lynkvis-ai-logo.png",
          logoAlt: "Lynkvis AI 官方标志",
          logoWidth: 1254,
          logoHeight: 1254,
        },
        {
          id: "private-slot-01",
          kind: "placeholder",
          eyebrow: "VISUAL PLACEHOLDER / 纯视觉占位",
          mark: "VISUAL 01",
          name: "匿名视觉展示位",
          note: "纯视觉占位，不对应具体客户、合作或公开品牌，不构成品牌背书",
        },
        {
          id: "private-slot-02",
          kind: "placeholder",
          eyebrow: "VISUAL PLACEHOLDER / 纯视觉占位",
          mark: "VISUAL 02",
          name: "匿名视觉展示位",
          note: "纯视觉占位，不对应具体客户、合作或公开品牌，不构成品牌背书",
        },
        {
          id: "private-slot-03",
          kind: "placeholder",
          eyebrow: "VISUAL PLACEHOLDER / 纯视觉占位",
          mark: "VISUAL 03",
          name: "匿名视觉展示位",
          note: "纯视觉占位，不对应具体客户、合作或公开品牌，不构成品牌背书",
        },
        {
          id: "private-slot-04",
          kind: "placeholder",
          eyebrow: "VISUAL PLACEHOLDER / 纯视觉占位",
          mark: "VISUAL 04",
          name: "匿名视觉展示位",
          note: "纯视觉占位，不对应具体客户、合作或公开品牌，不构成品牌背书",
        },
        {
          id: "private-slot-05",
          kind: "placeholder",
          eyebrow: "VISUAL PLACEHOLDER / 纯视觉占位",
          mark: "VISUAL 05",
          name: "匿名视觉展示位",
          note: "纯视觉占位，不对应具体客户、合作或公开品牌，不构成品牌背书",
        },
        {
          id: "disclosure",
          kind: "policy",
          eyebrow: "DISCLOSURE POLICY / 披露原则",
          mark: "未完整展示",
          name: "其余合作品牌与客户信息",
          note: "因保密约定不公开名称、Logo、项目资料与业务数据",
        },
        {
          id: "next",
          kind: "cta",
          eyebrow: "NEXT COLLABORATION / 下一次合作",
          mark: "YOUR TEAM",
          name: "带着一个具体难题来聊",
          note: "先判断价值、可行性与合作边界",
        },
      ],
    },
    caseStudy: {
      label: "SELECTED WORK",
      labelLocal: "项目实战",
      kicker: "AI APPLICATIONS / PLATFORM ENGINEERING",
      title: ["真实项目不只看界面，", "更要看它如何落地。"],
      intro:
        "每个案例都说明它解决什么问题、系统如何运行、关键工程难点在哪里，以及我在项目中的角色。可直接选择案例，也可用左右按钮切换，找到与你最接近的场景。",
      previous: "上一个案例",
      next: "下一个案例",
      selectorLabel: "快速选择案例",
      keyboardHint: "聚焦案例后，可使用左右方向键切换；Home 和 End 跳到首尾案例。",
      imageLabel: "PROJECT MATERIAL / 项目资料",
      roleLabel: "MY ROLE / 我的角色",
      discuss: "聊聊我的类似需求",
      disclosure:
        "以下包含独立开发与团队项目，角色与公开事实均按本人简历及授权信息标注。页面不披露客户敏感资料、团队成员信息或未经确认的结果。",
      projects: [
        {
          id: "lynkvis-ai",
          number: "CASE 01",
          year: "2026.04—2026.07",
          category: "AI SaaS / 室内设计",
          purpose: "室内设计 AI 出图与工作流",
          imageSrc: "/cases/lynkvis-ai-live.webp",
          imageAlt: "Lynkvis AI 公开灵感广场页面实机截图，展示作品搜索、分类筛选与设计作品瀑布流",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "Lynkvis AI 公开「灵感广场」页面实机截图 · 截取于 2026-08-18",
          title: "Lynkvis AI 室内设计出图平台",
          summary:
            "面向室内设计师，将参考图导入、风格化出图、AI 生图/生视频、图像编辑、素材管理与 Agent 工作流放进统一 SaaS 产品。",
          flow: ["BRIEF", "PROVIDER", "QUEUE", "DELIVER"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "室内设计需求与参考图 → 30+ 模型/厂商 Provider 适配 → 任务提交 → Redis Stream 异步调度 → 结果回写 → 素材库与运营管理。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "独立完成用户端、运营管理端和 Java 后端，统一模型参数、任务状态与异常处理，并接通积分、VIP 与权益发放链路。",
            },
            {
              id: "evidence",
              label: "简历记录",
              value:
                "覆盖 AI 出图/生视频、图像编辑、模板中心、素材库与 Agent 工作流；项目记录的 AI 任务成功率约 90%。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Java 17 / Spring Boot 3 / Redis Stream / MySQL / Vue 3 / Pinia / Ant Design Vue",
            },
          ],
          role: "独立全栈开发",
          roleNote: "简历记录：独立完成用户端、运营管理端与 Java 后端开发，并负责需求拆解、接口设计、联调排错、测试补全和交付。",
          tagsLabel: "Lynkvis AI 项目技术标签",
          tags: ["AI SAAS", "MODEL PROVIDER", "REDIS STREAM", "VUE 3"],
          externalUrl: "https://linktelai.com/",
          externalLabel: "访问线上项目",
        },
        {
          id: "ecommerce-research-agent",
          number: "CASE 02",
          year: "2026.03—2026.04",
          category: "AI Agent / 电商研究",
          purpose: "跨平台选品与内容机会发现",
          imageSrc: "/cases/ecommerce-research-agent-concept.webp",
          imageAlt: "电商选品与内容自动化 Agent 概念视觉，展示多平台信号汇聚、分析处理、机会输出与证据回溯链路",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "根据简历项目描述生成的概念视觉 · 非真实产品截图",
          title: "电商选品与内容自动化 Agent",
          summary:
            "从多平台用户讨论与长尾关键词中识别选品机会、用户痛点和内容方向，输出保留来源证据的 HTML/JSON 结构化报告。",
          flow: ["EXPAND", "COLLECT", "SCORE", "REPORT"],
          facts: [
            {
              id: "flow",
              label: "Agent 流程",
              value:
                "关键词扩展 → 抖音、微博、小红书、知乎等平台数据采集 → 原始数据清洗 → 需求信号识别 → 机会评分 → HTML/JSON 报告。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "将选品机会、内容选题、用户痛点、证据来源与运营建议定义为结构化输出，并保留标题、评论、上下文和平台来源以便追溯。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Python / Codex / Playwright / CloakBrowser / JSON / HTML Report / Keyword Strategy",
            },
          ],
          role: "独立开发",
          roleNote: "简历记录：基于 needs-collector 改造为 Codex 驱动的自动化 Agent，并独立实现多平台研究工作流、长尾关键词策略、Agent 分析结构和自动化报告输出。",
          tagsLabel: "电商研究 Agent 项目技术标签",
          tags: ["AI AGENT", "RESEARCH PIPELINE", "EVIDENCE", "HTML REPORT"],
        },
        {
          id: "enterprise-rag-mcp-assistant",
          number: "CASE 03",
          year: "2025.12—2026.02",
          category: "企业 AI / RAG + MCP",
          purpose: "文档与 ERP/WMS 统一问答",
          imageSrc: "/cases/enterprise-rag-mcp-assistant-concept.webp",
          imageAlt: "复能助手企业级 RAG 与 MCP Agent 概念视觉，展示文档检索、业务工具调用、中央编排与引用溯源",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "根据简历项目描述生成的概念视觉 · 非真实产品截图",
          title: "复能助手：企业级 RAG + MCP Agent",
          summary:
            "将企业文档、ERP 订单、WMS 库存与报表数据接入统一问答链路，支持业务查询、知识溯源和分析报告生成。",
          flow: ["DOCS", "RETRIEVE", "TOOL", "ANSWER"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "PDF 文档解析与 Milvus 检索 + MCP 数据库工具查询 ERP/WMS → Spring AI 编排 → Qwen3-72B 生成 → Vue 3 流式展示与引用溯源。",
            },
            {
              id: "evidence",
              label: "简历记录",
              value:
                "使用 5000 条业务样本完成 LoRA 微调，接入 20 份 PDF；项目记录问答准确率约 90%，常规分析报告约 5 分钟生成。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Java / Spring Boot / Spring AI / MCP / Milvus / Qwen3-72B / LLaMA-Factory / LoRA / Vue 3",
            },
          ],
          role: "全栈开发 / AI 应用开发",
          roleNote: "简历记录：参与 Spring AI 接入、RAG 检索、MCP 数据库工具、流式回答、模型微调部署与企业业务问答链路开发。",
          tagsLabel: "企业 RAG + MCP 助手项目技术标签",
          tags: ["RAG", "MCP", "MILVUS", "QWEN3-72B"],
        },
        {
          id: "mental-health-platform",
          number: "CASE 04",
          year: "2026",
          category: "行业 SaaS / AI 应用",
          purpose: "心理服务数字化闭环",
          imageSrc: "/cases/mental-health-platform.png",
          imageAlt: "大白 AI 心理健康平台项目宣传图，展示 AI 咨询、组织心理画像、风险预警与快速筛查",
          imageWidth: 903,
          imageHeight: 502,
          imageNote: "已授权项目宣传图",
          title: "大白 AI 心理健康平台",
          summary:
            "把咨询、测评、风险预警与交易串成一套可持续服务闭环，让用户体验与运营状态在同一系统中推进。",
          flow: ["ASSESS", "CHAT", "SERVICE", "DELIVER"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "服务发现与网关 → 用户及会话状态 → SSE 流式 AI 对话 → 测评与报告 → 咨询、交易及支付 → 持续交付。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "让对话、测评、咨询和交易共享可追踪状态，并处理异步回调、超时、支付幂等、发布检查与回滚。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Spring Cloud / SSE / MongoDB / Payment / Vue 3 / CI/CD",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者，推动业务目标、工程方案与交付节奏对齐；敏感信息按授权范围披露。",
          tagsLabel: "大白 AI 项目技术标签",
          tags: ["AI CONSULTATION", "SSE", "TRANSACTION STATE", "CI/CD"],
        },
        {
          id: "industrial-compliance-platform",
          number: "CASE 05",
          year: "2025—2026",
          category: "私有 AI / RAG 平台",
          purpose: "私有知识检索与溯源",
          imageSrc: "/cases/industrial-compliance-platform.png",
          imageAlt: "工业合规知识平台界面截图，展示区域风险趋势、风险分布热力图与雷达图",
          imageWidth: 1859,
          imageHeight: 912,
          imageNote: "已授权项目界面截图",
          title: "工业合规知识平台",
          summary:
            "让分散且敏感的合规资料在内网中可搜索、可追溯、可更新，为一线判断提供有来源的答案。",
          flow: ["DOCS", "PARSE", "INDEX", "ANSWER"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "文档接入 → 解析、清洗与分块 → 异步向量化 → 混合检索与重排 → 本地模型生成 → 原文追溯。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "构建可重跑的文档流水线、可恢复的异步向量任务，以及内网模型部署、依赖降级和答案溯源能力。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Java 17 / RAG / Redis Stream / Vector Search / Local LLM / Kubernetes",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者，推动业务目标、工程方案与交付节奏对齐；敏感信息按授权范围披露。",
          tagsLabel: "工业合规项目技术标签",
          tags: ["PRIVATE AI", "HYBRID SEARCH", "LOCAL LLM", "KUBERNETES"],
        },
        {
          id: "sre-copilot",
          number: "CASE 06",
          year: "2025",
          category: "AI Agent / 可观测性",
          purpose: "可审计的智能故障诊断",
          imageSrc: "/cases/sre-copilot.png",
          imageAlt: "智能 SRE 运维助手界面截图，展示 Kubernetes 调查时间线、日志与支持证据",
          imageWidth: 1859,
          imageHeight: 903,
          imageNote: "已授权项目界面截图",
          title: "智能 SRE 运维助手",
          summary:
            "把指标、日志与集群事件串成可追踪的调查链路，帮助运维团队更快聚焦线索，同时保留人工判断与工具边界。",
          flow: ["OBSERVE", "REASON", "ACT", "REPORT"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "问题输入 → 调查计划 → 工具作用域校验 → 指标、日志与 Kubernetes 查询 → 流式证据 → 诊断总结。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "明确集群、命名空间与时间窗口边界，将计划和工具调用保存为可观察事件，并支持中断、执行上限与模型降级。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Spring Boot 3 / React / AI Agent / MCP / Prometheus / Kubernetes",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者，推动业务目标、工程方案与交付节奏对齐；敏感信息按授权范围披露。",
          tagsLabel: "SRE 助手项目技术标签",
          tags: ["AI AGENT", "MCP", "PROMETHEUS", "KUBERNETES"],
        },
        {
          id: "content-orchestration",
          number: "CASE 07",
          year: "2025—2026",
          category: "AIGC 基础设施 / 任务编排",
          purpose: "规模化内容生产调度",
          imageSrc: "/cases/content-orchestration-schematic.png",
          imageAlt: "生成式内容调度平台的任务接入、优先级队列、模型网关与实时进度链路示意图，非实机截图",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "本站调度链路示意图 · 非实机截图",
          title: "生成式内容调度平台",
          summary:
            "把分散的批量生成任务集中到统一工作台，统一输入、模型、队列与进度，降低规模化生产的操作复杂度。",
          flow: ["IMPORT", "QUEUE", "MODEL", "EXPORT"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "表格导入 → 模板变量与任务校验 → 分级队列 → 多模型网关 → 重试与状态流转 → WebSocket 进度 → 结果导出。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "统一输入校验和任务标准，管理优先级、队列积压与失败重试，隔离模型供应方差异并实时反馈进度。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "NestJS / TypeScript / Redis Stream / WebSocket / Vue 3 / Docker",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者，推动业务目标、工程方案与交付节奏对齐；敏感信息按授权范围披露。",
          tagsLabel: "生成式内容调度项目技术标签",
          tags: ["TASK QUEUE", "MODEL GATEWAY", "WEBSOCKET", "DOCKER"],
        },
      ],
    },
    process: {
      label: "PROCESS",
      labelLocal: "合作流程",
      kicker: "DISCOVER. PROTOTYPE. DEPLOY. ITERATE.",
      title: ["先用小成本验证，", "再把有效方案推到生产。"],
      steps: [
        { id: "discover", number: "01", tag: "DISCOVER", title: "对齐结果与边界", description: "明确要改善的业务结果、真实用户、可用数据和不可触碰的约束。" },
        { id: "prototype", number: "02", tag: "PROTOTYPE", title: "用原型消除最大风险", description: "先验证最关键的流程和效果，让继续、调整或停止都有依据。" },
        { id: "deploy", number: "03", tag: "DEPLOY", title: "接入现有系统上线", description: "补齐数据、权限、异常、测试与发布链路，把 Demo 变成可运行产品。" },
        { id: "iterate", number: "04", tag: "ITERATE", title: "用真实使用持续优化", description: "依据反馈改善流程、体验与模型，并完成文档和团队交接。" },
      ],
    },
    about: {
      label: "PHILOSOPHY",
      labelLocal: "我的理念",
      quote: "“不以 Demo 交差，让 AI 在真实业务里被用起来、跑得稳定。”",
      body: "我会先判断一个场景是否值得做，再选择足够简单、能够验证的方案。真正的交付不仅是代码，还包括业务采用、数据与权限边界、运行稳定性，以及团队接得住的长期维护方式。",
    },
    contact: {
      label: "CONTACT",
      labelLocal: "开始合作",
      status: "当前可承接 AI 落地合作",
      titleStart: "把你的业务问题，",
      titleEnd: "变成下一项上线成果。",
      body: "已有明确场景，可以带上当前卡点与期望结果；还不确定从哪里开始，也可以先描述业务流程。你可以发邮件附上信息，也可以扫描微信二维码先聊。",
      emailListLabel: "联系邮箱",
      emailAria: "发送合作邮件到",
      wechatLabel: "WECHAT / 个人微信",
      wechatTitle: "扫码添加个人微信",
      wechatNote: "微信资料所在地：瑞典 西曼兰。电脑端可直接扫码；手机端可长按保存后在微信识别。",
      wechatImageAlt: "风雨的个人微信二维码",
      copyIdle: "复制合作沟通模板",
      copyWorking: "正在复制合作模板",
      copyDone: "合作模板已复制",
      copyFailed: "复制失败，请重试",
      copyCodeIdle: "COPY BRIEF",
      copyCodeWorking: "COPYING",
      copyCodeDone: "COPIED",
      copyCodeFailed: "RETRY",
      liveDone: "合作沟通模板已复制到剪贴板",
      liveFailed: "复制失败，请重试",
      mailSubject: "AI 落地项目合作｜业务场景初步沟通",
      mailTemplate: `你好风雨，我想沟通一个 AI 落地项目。\n\n业务场景与使用者：\n当前问题：\n已有数据或系统：\n期望结果：\n计划时间：\n预算范围（可选）：`,
    },
    footer: {
      tagline: "从真实问题出发，交付可运行的 AI。",
      backToTop: "返回顶部 ↑",
    },
  },
  en: {
    seo: {
      title: "Fengyu | FDE for AI Product Delivery",
      description:
        "Fengyu is a Forward Deployed Engineer helping teams identify AI use cases worth building, validate them with working prototypes, integrate systems, and ship reliable products.",
    },
    preferences: {
      group: "Language and theme settings",
      switchToEnglish: "Switch to English",
      switchToChinese: "切换为中文",
      switchToLight: "Switch to light mode",
      switchToDark: "Switch to dark mode",
      changedToEnglish: "Language changed to English",
      changedToChinese: "语言已切换为中文",
    },
    header: {
      home: "Fengyu home",
      availability: "Available for AI delivery projects",
      navLabel: "Primary navigation",
      services: "Services",
      partners: "Partners",
      caseStudy: "Case studies",
      process: "How we work",
      about: "About",
      contact: "Start a project",
      contactShort: "Talk",
    },
    hero: {
      index: "DISCOVER / PROTOTYPE / DEPLOY / ITERATE — 2026",
      kicker: "FORWARD DEPLOYED ENGINEER / FIELD TO PRODUCTION",
      kickerAside: "AI SOLUTIONS / PRODUCT / DELIVERY",
      title: [
        { text: "Turn real problems", outlined: false },
        { text: "into AI that ships", outlined: true },
        { text: "and keeps working.", outlined: false },
      ],
      label: "00 / INTRODUCTION",
      intro:
        "I’m Fengyu, a Forward Deployed Engineer. Bring the real workflow; I connect users, data, models and existing systems—validate value first, then ship with the controls production requires.",
      cta: "Discuss your AI use case",
      scroll: "Scroll to explore",
    },
    ticker: {
      aria: "Core capabilities",
      items: ["Use-case discovery", "Working prototypes", "Data and system integration", "Production launch", "Operational improvement"],
    },
    servicesSection: {
      label: "SERVICES",
      labelLocal: "What I deliver",
      kicker: "FROM FIELD TO PRODUCTION",
      title: ["Start with one real problem.", "Deliver something that works."],
    },
    services: [
      {
        id: "discovery",
        number: "01",
        tag: "DISCOVERY & STRATEGY",
        title: "AI use-case discovery & roadmap",
        description: "For teams that see AI potential but do not know what to build first. Find the highest-value entry point before committing to development.",
        items: ["Workflow and critical bottlenecks", "Use-case priority and risk assessment", "Phased roadmap and delivery boundaries"],
      },
      {
        id: "prototype",
        number: "02",
        tag: "PROTOTYPE & VALIDATE",
        title: "Working prototypes & value validation",
        description: "For projects that need to reduce uncertainty. Test the workflow, quality and adoption with real data before making the full investment.",
        items: ["Usable workflow or agent", "Real data and tool integration", "Evaluation and go-forward criteria"],
      },
      {
        id: "delivery",
        number: "03",
        tag: "INTEGRATE & DEPLOY",
        title: "System integration & production launch",
        description: "For teams with a demo stuck before launch. Connect the solution to existing data, permissions and business systems, then make it maintainable.",
        items: ["Full-stack product and critical paths", "Enterprise system, data and model integration", "Testing, release and operational monitoring"],
      },
      {
        id: "iteration",
        number: "04",
        tag: "ADOPT & ITERATE",
        title: "Operational improvement & handoff",
        description: "For systems already live but not yet reliable in use. Improve them around real feedback and transfer the capability back to the team.",
        items: ["Usage feedback and issue review", "Workflow, experience and model improvement", "Documentation and capability handoff"],
      },
    ],
    serviceAria: "Learn about and discuss",
    capabilitiesSection: {
      label: "CAPABILITIES",
      labelLocal: "How I contribute",
      title: ["Understands the business.", "Finishes the system.", "Owns the path to launch."],
      intro: "You should not have to translate between consultants, product and engineering. I turn the business goal into a testable plan and carry one responsibility chain through launch and handoff.",
    },
    capabilities: [
      { id: "field", number: "01", title: "Define the right problem", description: "Enter the real workflow and find the bottleneck that changes outcomes instead of forcing a model-first idea." },
      { id: "prototype", number: "02", title: "Make value visible early", description: "Build something usable and measurable, so the team has evidence to continue, adjust or stop." },
      { id: "integration", number: "03", title: "Connect the critical workflow", description: "Join frontend, backend, data, enterprise systems and models so the solution fits existing work." },
      { id: "production", number: "04", title: "Own the path to launch", description: "Cover permissions, evaluation, logs, release and handoff so the system remains controllable after launch." },
    ],
    partners: {
      label: "TRUST & COLLABORATION",
      labelLocal: "Collaboration and disclosure",
      kicker: "VERIFIED BRANDS / VISUAL PLACEHOLDERS",
      title: ["Trust is built through delivery", "and clear boundaries."],
      intro: "The moving wall shows selected collaboration and product brands approved for disclosure alongside clearly labeled visual placeholders. A visual placeholder does not identify any specific client, collaboration or public brand and is not an endorsement. This is not a complete record: other brands, client names, project materials and business data remain undisclosed under confidentiality agreements.",
      aria: "Disclosed brands and visual placeholders; placeholders are not client, collaboration or brand endorsements",
      pauseMotion: "Pause brand wall",
      tiles: [
        { id: "funeng-rare-earth", kind: "brand", eyebrow: "CONFIRMED COLLABORATION", mark: "复能稀土", name: "宁波复能稀土新材料股份有限公司", note: "Confirmed collaboration brand approved for public display" },
        { id: "chenghui-tech", kind: "brand", eyebrow: "CONFIRMED COLLABORATION", mark: "橙绘科技", name: "温州橙绘科技有限公司", note: "Confirmed collaboration brand approved for public display" },
        {
          id: "lynkvis-ai",
          kind: "brand",
          eyebrow: "PRODUCT DELIVERY",
          mark: "LYNKVIS AI",
          name: "Lynkvis AI",
          note: "Interior-design AI product and full-stack delivery",
          logoSrc: "/brands/lynkvis-ai-logo.png",
          logoAlt: "Official Lynkvis AI logo",
          logoWidth: 1254,
          logoHeight: 1254,
        },
        { id: "private-slot-01", kind: "placeholder", eyebrow: "VISUAL PLACEHOLDER", mark: "VISUAL 01", name: "Anonymous visual slot", note: "Visual placeholder only; it does not identify a client, collaboration or public brand and is not an endorsement" },
        { id: "private-slot-02", kind: "placeholder", eyebrow: "VISUAL PLACEHOLDER", mark: "VISUAL 02", name: "Anonymous visual slot", note: "Visual placeholder only; it does not identify a client, collaboration or public brand and is not an endorsement" },
        { id: "private-slot-03", kind: "placeholder", eyebrow: "VISUAL PLACEHOLDER", mark: "VISUAL 03", name: "Anonymous visual slot", note: "Visual placeholder only; it does not identify a client, collaboration or public brand and is not an endorsement" },
        { id: "private-slot-04", kind: "placeholder", eyebrow: "VISUAL PLACEHOLDER", mark: "VISUAL 04", name: "Anonymous visual slot", note: "Visual placeholder only; it does not identify a client, collaboration or public brand and is not an endorsement" },
        { id: "private-slot-05", kind: "placeholder", eyebrow: "VISUAL PLACEHOLDER", mark: "VISUAL 05", name: "Anonymous visual slot", note: "Visual placeholder only; it does not identify a client, collaboration or public brand and is not an endorsement" },
        { id: "disclosure", kind: "policy", eyebrow: "DISCLOSURE POLICY", mark: "NOT A COMPLETE LIST", name: "Other collaboration brands and client information", note: "Names, logos, project materials and business data remain undisclosed under confidentiality agreements" },
        { id: "next", kind: "cta", eyebrow: "NEXT COLLABORATION", mark: "YOUR TEAM", name: "Bring one concrete problem", note: "Start with value, feasibility and delivery boundaries" },
      ],
    },
    caseStudy: {
      label: "SELECTED WORK",
      labelLocal: "Case studies",
      kicker: "AI APPLICATIONS / PLATFORM ENGINEERING",
      title: ["Real projects are more than screens.", "See how they reach production."],
      intro:
        "Each case explains the problem it solves, how the system works, where the engineering gets hard, and my role in delivery. Choose a case directly or use the arrows to find the scenario closest to yours.",
      previous: "Previous case",
      next: "Next case",
      selectorLabel: "Choose a case study",
      keyboardHint: "Focus the case and use Left or Right Arrow to switch; Home and End jump to the first or last case.",
      imageLabel: "PROJECT MATERIAL",
      roleLabel: "MY ROLE",
      discuss: "Discuss a similar need",
      disclosure:
        "This selection includes independent and team projects. Roles and public facts follow Fengyu's resume and approved information; client-sensitive material, team details and unverified outcomes are not disclosed.",
      projects: [
        {
          id: "lynkvis-ai",
          number: "CASE 01",
          year: "2026.04–2026.07",
          category: "AI SaaS / Interior Design",
          purpose: "AI design generation and workflows",
          imageSrc: "/cases/lynkvis-ai-live.webp",
          imageAlt: "Live screenshot of the public Lynkvis AI Inspiration Gallery showing search, category filters and a masonry grid of design work",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "Live screenshot of the public Lynkvis AI Inspiration Gallery · captured 2026-08-18",
          title: "Lynkvis AI Interior Design Platform",
          summary:
            "Bring reference import, style-controlled generation, AI image and video creation, image editing, asset management and Agent workflows into one SaaS product for interior designers.",
          flow: ["BRIEF", "PROVIDER", "QUEUE", "DELIVER"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Interior design brief and reference → adapters for 30+ models and vendors → task submission → Redis Stream orchestration → result persistence → asset and operations management.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Independently delivered the user app, operations console and Java backend, normalizing model parameters, task state and failure handling while connecting points, VIP and entitlement flows.",
            },
            {
              id: "evidence",
              label: "Resume record",
              value:
                "Scope includes AI image/video generation, image editing, templates, an asset library and Agent workflows; the project records an AI task success rate of about 90%.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Java 17 / Spring Boot 3 / Redis Stream / MySQL / Vue 3 / Pinia / Ant Design Vue",
            },
          ],
          role: "Independent full-stack developer",
          roleNote: "Resume record: independently delivered the user app, operations console and Java backend, including requirements breakdown, API design, integration debugging, test completion and delivery.",
          tagsLabel: "Lynkvis AI project technology tags",
          tags: ["AI SAAS", "MODEL PROVIDER", "REDIS STREAM", "VUE 3"],
          externalUrl: "https://linktelai.com/",
          externalLabel: "Visit live project",
        },
        {
          id: "ecommerce-research-agent",
          number: "CASE 02",
          year: "2026.03–2026.04",
          category: "AI Agent / E-commerce Research",
          purpose: "Cross-platform product and content discovery",
          imageSrc: "/cases/ecommerce-research-agent-concept.webp",
          imageAlt: "Concept visual for an e-commerce research Agent showing multi-platform signals, analysis stages, opportunity outputs and traceable evidence paths",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "Concept visual generated from the resume project description · not a real product screenshot",
          title: "E-commerce Research & Content Agent",
          summary:
            "Identify product opportunities, user pain points and content directions from multi-platform discussions and long-tail keywords, then deliver traceable HTML and JSON reports.",
          flow: ["EXPAND", "COLLECT", "SCORE", "REPORT"],
          facts: [
            {
              id: "flow",
              label: "Agent flow",
              value:
                "Keyword expansion → collection across Douyin, Weibo, Xiaohongshu and Zhihu → raw-data cleaning → demand-signal detection → opportunity scoring → HTML/JSON report.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Define product opportunities, content topics, pain points, evidence sources and operating suggestions as structured outputs while preserving titles, comments, context and platform provenance.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Python / Codex / Playwright / CloakBrowser / JSON / HTML Report / Keyword Strategy",
            },
          ],
          role: "Independent developer",
          roleNote: "Resume record: the project was adapted from needs-collector into a Codex-driven e-commerce automation Agent; independent work covered the multi-platform research workflow, long-tail keyword strategy, Agent output structure and automated HTML/JSON reporting.",
          tagsLabel: "E-commerce research Agent technology tags",
          tags: ["AI AGENT", "RESEARCH PIPELINE", "EVIDENCE", "HTML REPORT"],
        },
        {
          id: "enterprise-rag-mcp-assistant",
          number: "CASE 03",
          year: "2025.12–2026.02",
          category: "Enterprise AI / RAG + MCP",
          purpose: "Unified document and ERP/WMS answers",
          imageSrc: "/cases/enterprise-rag-mcp-assistant-concept.webp",
          imageAlt: "Concept visual for 复能助手, an enterprise RAG and MCP Agent, showing document retrieval, business-tool access, central orchestration and citation traceability",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "Concept visual generated from the resume project description · not a real product screenshot",
          title: "复能助手 — Enterprise RAG + MCP Assistant",
          summary:
            "Connect enterprise documents, ERP orders, WMS inventory and reporting data in one answer flow for business queries, source-traceable answers and analytical reports.",
          flow: ["DOCS", "RETRIEVE", "TOOL", "ANSWER"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "PDF parsing and Milvus retrieval + MCP database tools for ERP/WMS → Spring AI orchestration → Qwen3-72B generation → Vue 3 streaming presentation with source traceability.",
            },
            {
              id: "evidence",
              label: "Resume record",
              value:
                "LoRA fine-tuning used 5,000 business samples and the knowledge base ingested 20 PDFs; the project records about 90% answer accuracy and roughly five minutes for a standard analysis report.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Java / Spring Boot / Spring AI / MCP / Milvus / Qwen3-72B / LLaMA-Factory / LoRA / Vue 3",
            },
          ],
          role: "Full-stack / AI application developer",
          roleNote: "Resume record: contributed to Spring AI integration, RAG retrieval, MCP database tools, streaming answers, model fine-tuning deployment and the enterprise Q&A workflow.",
          tagsLabel: "Enterprise RAG and MCP assistant technology tags",
          tags: ["RAG", "MCP", "MILVUS", "QWEN3-72B"],
        },
        {
          id: "mental-health-platform",
          number: "CASE 04",
          year: "2026",
          category: "Industry SaaS / AI Application",
          purpose: "End-to-end mental health services",
          imageSrc: "/cases/mental-health-platform.png",
          imageAlt: "Dabai AI mental health platform project visual showing AI consultation, organizational wellbeing profiles, risk alerts and rapid screening",
          imageWidth: 903,
          imageHeight: 502,
          imageNote: "Authorized project promotional visual",
          title: "Dabai AI Mental Health Platform",
          summary:
            "Connect consultation, assessment, risk alerts and transactions in one service loop, keeping the user experience and operational state in the same system.",
          flow: ["ASSESS", "CHAT", "SERVICE", "DELIVER"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Service discovery and gateway → user and session state → SSE-based AI conversations → assessments and reports → consultation, transaction and payment → continuous delivery.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Traceable state across conversations, assessments, consultations and transactions, with asynchronous callbacks, timeout handling, payment idempotency, release checks and rollback readiness.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Spring Cloud / SSE / MongoDB / Payment / Vue 3 / CI/CD",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead, aligning business goals, engineering decisions and delivery cadence; sensitive details follow agreed disclosure boundaries.",
          tagsLabel: "Dabai AI project technology tags",
          tags: ["AI CONSULTATION", "SSE", "TRANSACTION STATE", "CI/CD"],
        },
        {
          id: "industrial-compliance-platform",
          number: "CASE 05",
          year: "2025–2026",
          category: "Private AI / RAG Platform",
          purpose: "Private knowledge retrieval and traceability",
          imageSrc: "/cases/industrial-compliance-platform.png",
          imageAlt: "Industrial compliance knowledge platform interface showing regional risk trends, a risk heat map and radar chart",
          imageWidth: 1859,
          imageHeight: 912,
          imageNote: "Authorized project interface capture",
          title: "Industrial Compliance Knowledge Platform",
          summary:
            "Make fragmented, sensitive compliance material searchable, traceable and maintainable inside the private environment, with source-backed answers for frontline decisions.",
          flow: ["DOCS", "PARSE", "INDEX", "ANSWER"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Document ingestion → parsing, cleaning and chunking → asynchronous embedding → hybrid retrieval and reranking → local-model generation → source traceability.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Re-runnable document pipelines, recoverable asynchronous embedding tasks, private model deployment, graceful degradation and source-backed answers.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Java 17 / RAG / Redis Stream / Vector Search / Local LLM / Kubernetes",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead, aligning business goals, engineering decisions and delivery cadence; sensitive details follow agreed disclosure boundaries.",
          tagsLabel: "Industrial compliance project technology tags",
          tags: ["PRIVATE AI", "HYBRID SEARCH", "LOCAL LLM", "KUBERNETES"],
        },
        {
          id: "sre-copilot",
          number: "CASE 06",
          year: "2025",
          category: "AI Agent / Observability",
          purpose: "Auditable incident diagnosis",
          imageSrc: "/cases/sre-copilot.png",
          imageAlt: "Intelligent SRE operations assistant interface showing a Kubernetes investigation timeline, logs and supporting evidence",
          imageWidth: 1859,
          imageHeight: 903,
          imageNote: "Authorized project interface capture",
          title: "Intelligent SRE Operations Assistant",
          summary:
            "Turn metrics, logs and cluster events into a traceable investigation flow that narrows the search faster while preserving human judgment and tool boundaries.",
          flow: ["OBSERVE", "REASON", "ACT", "REPORT"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "User question → investigation plan → tool-scope validation → metrics, logs and Kubernetes queries → streamed evidence → diagnostic summary.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Explicit cluster, namespace and time-window boundaries, observable tool events, interruption, execution limits and model fallback.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Spring Boot 3 / React / AI Agent / MCP / Prometheus / Kubernetes",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead, aligning business goals, engineering decisions and delivery cadence; sensitive details follow agreed disclosure boundaries.",
          tagsLabel: "SRE assistant project technology tags",
          tags: ["AI AGENT", "MCP", "PROMETHEUS", "KUBERNETES"],
        },
        {
          id: "content-orchestration",
          number: "CASE 07",
          year: "2025–2026",
          category: "AIGC Infrastructure / Orchestration",
          purpose: "Content production at scale",
          imageSrc: "/cases/content-orchestration-schematic.png",
          imageAlt: "Non-production schematic of task intake, priority queues, a model gateway and live progress for the generative content orchestration platform",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "On-site orchestration schematic · not a production screenshot",
          title: "Generative Content Orchestration Platform",
          summary:
            "Bring fragmented batch-generation work into one workspace, standardizing inputs, model access, queues and progress while reducing operational complexity at scale.",
          flow: ["IMPORT", "QUEUE", "MODEL", "EXPORT"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Spreadsheet import → template variables and validation → priority queues → multi-model gateway → retries and state transitions → WebSocket progress → export.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Standardized validation and task definitions, queue pressure and retry management, provider abstraction and real-time execution feedback.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "NestJS / TypeScript / Redis Stream / WebSocket / Vue 3 / Docker",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead, aligning business goals, engineering decisions and delivery cadence; sensitive details follow agreed disclosure boundaries.",
          tagsLabel: "Generative content orchestration technology tags",
          tags: ["TASK QUEUE", "MODEL GATEWAY", "WEBSOCKET", "DOCKER"],
        },
      ],
    },
    process: {
      label: "PROCESS",
      labelLocal: "How we work",
      kicker: "DISCOVER. PROTOTYPE. DEPLOY. ITERATE.",
      title: ["Validate with a smaller bet.", "Scale only what proves useful."],
      steps: [
        { id: "discover", number: "01", tag: "DISCOVER", title: "Align on outcomes and boundaries", description: "Define the result to improve, the real users, available data and constraints that cannot be crossed." },
        { id: "prototype", number: "02", tag: "PROTOTYPE", title: "Remove the biggest risk first", description: "Validate the critical workflow and quality so the team has evidence to continue, adjust or stop." },
        { id: "deploy", number: "03", tag: "DEPLOY", title: "Integrate with existing systems", description: "Complete data, permissions, failure handling, testing and release so the demo becomes an operating product." },
        { id: "iterate", number: "04", tag: "ITERATE", title: "Improve through real usage", description: "Use feedback to refine the workflow, experience and model, then complete documentation and handoff." },
      ],
    },
    about: {
      label: "PHILOSOPHY",
      labelLocal: "What I believe",
      quote: "“The goal is not a convincing demo. It is AI that gets used and keeps working.”",
      body: "I first ask whether a use case is worth building, then choose the simplest path that can prove it. Delivery includes more than code: adoption, data and permission boundaries, reliability, and a maintenance model the team can own.",
    },
    contact: {
      label: "CONTACT",
      labelLocal: "Start a project",
      status: "Available for AI delivery projects",
      titleStart: "Turn your business problem",
      titleEnd: "into the next shipped outcome.",
      body: "If you have a defined use case, bring the current blocker and desired result. If you do not know where to start, describe the workflow. Email the details or scan the WeChat QR code to start a conversation.",
      emailListLabel: "Contact email addresses",
      emailAria: "Send a project email to",
      wechatLabel: "WECHAT / PERSONAL CONTACT",
      wechatTitle: "Add my personal WeChat",
      wechatNote: "WeChat profile location: Västmanland, Sweden. Scan on desktop; on mobile, press and hold to save and recognize it in WeChat.",
      wechatImageAlt: "Personal WeChat QR code for Fengyu",
      copyIdle: "Copy the project brief",
      copyWorking: "Copying the project brief",
      copyDone: "Project brief copied",
      copyFailed: "Copy failed. Try again",
      copyCodeIdle: "COPY BRIEF",
      copyCodeWorking: "COPYING",
      copyCodeDone: "COPIED",
      copyCodeFailed: "RETRY",
      liveDone: "The project brief was copied to your clipboard",
      liveFailed: "Copy failed. Please try again",
      mailSubject: "AI delivery project | Initial use-case discussion",
      mailTemplate: `Hi Fengyu, I’d like to discuss an AI delivery project.\n\nBusiness context and users:\nCurrent problem:\nExisting data or systems:\nDesired outcome:\nTarget timeline:\nBudget range (optional):`,
    },
    footer: {
      tagline: "Start with a real problem. Deliver AI that works.",
      backToTop: "BACK TO TOP ↑",
    },
  },
} as const;
