export type Locale = "zh" | "en";

export const siteCopy = {
  zh: {
    seo: {
      title: "风雨 — 前沿部署工程师",
      description:
        "深入业务现场，从 AI 机会定义、原型验证到系统集成与生产部署，完成解决方案落地的最后一公里。",
    },
    preferences: {
      group: "语言与主题设置",
      switchToEnglish: "Switch to English",
      switchToChinese: "切换为中文",
      switchToLight: "切换至日间模式",
      switchToDark: "切换至夜间模式",
      changedToEnglish: "Language changed to English",
      changedToChinese: "语言已切换为中文",
    },
    header: {
      home: "风雨首页",
      availability: "可承接 FDE 项目",
      navLabel: "主导航",
      services: "服务",
      partners: "合作",
      caseStudy: "案例",
      process: "方法",
      about: "关于",
      contact: "聊聊合作",
      contactShort: "合作",
    },
    hero: {
      index: "发现 / 原型 / 部署 / 迭代 — 2026",
      kicker: "FORWARD DEPLOYED ENGINEER / 前沿部署工程师",
      kickerAside: "AI SOLUTIONS / PRODUCT / DELIVERY",
      title: [
        { text: "深入业务现场，", outlined: false },
        { text: "把 AI 变成", outlined: true },
        { text: "可运行的结果。", outlined: false },
      ],
      label: "00 / INTRODUCTION",
      intro:
        "我是风雨，一名前沿部署工程师。我与业务团队并肩，从问题定义到原型验证，再到生产系统集成，完成 AI 解决方案落地的最后一公里。",
      cta: "查看 FDE 工作方式",
      scroll: "向下探索",
    },
    ticker: {
      aria: "核心能力",
      items: ["业务共创", "AI 原型", "系统集成", "生产部署", "持续迭代"],
    },
    servicesSection: {
      label: "SERVICES",
      labelLocal: "服务能力",
      kicker: "FROM FIELD TO PRODUCTION",
      title: ["从业务现场出发，", "让 AI 真正进入生产。"],
    },
    services: [
      {
        id: "discovery",
        number: "01",
        tag: "DISCOVERY & STRATEGY",
        title: "业务诊断与方案共创",
        description:
          "进入真实业务现场，和团队一起拆解目标、流程与约束，找到 AI 最值得落地的切入点。",
        items: ["业务流程与痛点访谈", "AI 机会与风险识别", "解决方案架构与价值定义"],
      },
      {
        id: "prototype",
        number: "02",
        tag: "PROTOTYPE & VALIDATE",
        title: "AI 原型与智能体验证",
        description:
          "用最短路径做出可用原型，在真实数据和用户反馈中验证效果，而不是停留在概念演示。",
        items: ["工作流与智能体原型", "工具调用与数据接入", "效果评测与安全边界"],
      },
      {
        id: "delivery",
        number: "03",
        tag: "INTEGRATE & DEPLOY",
        title: "生产集成与工程交付",
        description:
          "把验证通过的方案接入现有系统、数据与权限体系，完成从原型到生产的最后一公里。",
        items: ["全栈产品开发", "企业系统与模型集成", "测试、发布与可观测性"],
      },
      {
        id: "iteration",
        number: "04",
        tag: "ADOPT & ITERATE",
        title: "落地采用与持续迭代",
        description:
          "围绕真实使用结果持续优化体验、流程与模型，让解决方案被团队采用并长期产生价值。",
        items: ["使用反馈与数据复盘", "流程与模型持续优化", "能力沉淀与团队交接"],
      },
    ],
    serviceAria: "了解并咨询",
    capabilitiesSection: {
      label: "CAPABILITIES",
      labelLocal: "核心能力",
      title: ["既能进入", "业务现场，", "也能走到生产。"],
      intro:
        "FDE 连接客户、业务、产品与工程。我把不确定的 AI 机会拆成可验证原型，再把有效原型做成稳定系统。",
    },
    capabilities: [
      { id: "field", number: "01", title: "业务现场共创", description: "与一线用户和业务负责人并肩，把模糊诉求转成可验证问题。" },
      { id: "prototype", number: "02", title: "AI 快速原型", description: "把模型、工具和数据组合成可体验、可评测的工作流。" },
      { id: "integration", number: "03", title: "全栈系统集成", description: "连接前端、后端、企业系统与 AI 能力，打通关键链路。" },
      { id: "production", number: "04", title: "生产级交付", description: "覆盖权限、评测、日志、发布与迭代，让方案稳定进入生产。" },
    ],
    partners: {
      label: "TRUST & COLLABORATION",
      labelLocal: "合作品牌",
      kicker: "DISCLOSED WITH PERMISSION",
      title: ["被确认的合作，", "才值得成为品牌背书。"],
      intro:
        "公开品牌墙目前展示已确认参与的 WUDE 项目团队。公司客户名称与 Logo 仅在获得授权后加入，不用模糊标识夸大履历。",
      aria: "已公开的合作品牌与项目",
      tiles: [
        {
          id: "wude",
          kind: "brand",
          eyebrow: "CONFIRMED PARTICIPATION / 已确认参与",
          mark: "WUDE",
          name: "WUDE 项目团队",
          note: "工程作品与技术内容站",
        },
        {
          id: "disclosure",
          kind: "policy",
          eyebrow: "DISCLOSURE POLICY / 披露原则",
          mark: "授权后公开",
          name: "真实公司名称与 Logo",
          note: "仅展示经合作方许可的信息",
        },
        {
          id: "next",
          kind: "cta",
          eyebrow: "NEXT COLLABORATION / 下一次合作",
          mark: "YOUR TEAM",
          name: "成为下一个公开案例",
          note: "从一个真实业务问题开始",
        },
      ],
    },
    caseStudy: {
      label: "PARTICIPATED WORK",
      labelLocal: "系统案例",
      kicker: "AI APPLICATIONS / PLATFORM ENGINEERING",
      title: ["四个真实系统案例，", "直接在本站展开。"],
      intro:
        "从用户服务到知识检索、智能运维和内容调度，以下案例直接展示可核对的系统背景、工程链路与技术选择。",
      previous: "上一个案例",
      next: "下一个案例",
      keyboardHint: "聚焦案例后，可使用左右方向键切换；Home 和 End 跳到首尾案例。",
      imageLabel: "PROJECT MATERIAL / 项目资料",
      roleLabel: "MY ROLE / 我的角色",
      discuss: "沟通类似项目",
      disclosure:
        "以下为团队项目，风雨确认担任项目主导者。本站仅呈现可公开核对的系统信息；团队成员、客户敏感信息与量化结果仅在获得授权后披露。",
      projects: [
        {
          id: "mental-health-platform",
          number: "CASE 01",
          year: "2026",
          category: "行业 SaaS / AI 应用",
          purpose: "AI 心理健康服务",
          imageSrc: "/cases/mental-health-platform.png",
          imageAlt: "大白 AI 心理健康平台项目宣传图，展示 AI 咨询、组织心理画像、风险预警与快速筛查",
          imageWidth: 903,
          imageHeight: 502,
          imageNote: "已授权项目宣传图",
          title: "大白 AI 心理健康平台",
          summary:
            "面向个人与组织的心理健康产品，将 AI 咨询、心理画像、风险预警和快速筛查整合在同一套服务中。",
          flow: ["ASSESS", "CHAT", "SERVICE", "DELIVER"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "服务发现与网关 → 用户及会话状态 → SSE 流式 AI 对话 → 测评与报告 → 咨询、交易及支付 → 持续交付。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "让对话、测评、咨询和交易共享可追踪状态，并处理异步回调、超时、支付幂等、发布检查与回滚。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Spring Cloud / SSE / MongoDB / Payment / Vue 3 / CI/CD",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者；客户敏感信息与量化结果仅在获得授权后披露。",
          tagsLabel: "大白 AI 项目技术标签",
          tags: ["AI CONSULTATION", "SSE", "TRANSACTION STATE", "CI/CD"],
        },
        {
          id: "industrial-compliance-platform",
          number: "CASE 02",
          year: "2025—2026",
          category: "私有 AI / RAG 平台",
          purpose: "企业合规知识检索",
          imageSrc: "/cases/industrial-compliance-platform.png",
          imageAlt: "工业合规知识平台界面截图，展示区域风险趋势、风险分布热力图与雷达图",
          imageWidth: 1859,
          imageHeight: 912,
          imageNote: "已授权项目界面截图",
          title: "工业合规知识平台",
          summary:
            "面向内部合规资料的私有知识平台，使分散文档能够被加工、检索、追溯和重建。",
          flow: ["DOCS", "PARSE", "INDEX", "ANSWER"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "文档接入 → 解析、清洗与分块 → 异步向量化 → 混合检索与重排 → 本地模型生成 → 原文追溯。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "构建可重跑的文档流水线、可恢复的异步向量任务，以及内网模型部署、依赖降级和答案溯源能力。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Java 17 / RAG / Redis Stream / Vector Search / Local LLM / Kubernetes",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者；客户敏感信息与量化结果仅在获得授权后披露。",
          tagsLabel: "工业合规项目技术标签",
          tags: ["PRIVATE AI", "HYBRID SEARCH", "LOCAL LLM", "KUBERNETES"],
        },
        {
          id: "sre-copilot",
          number: "CASE 03",
          year: "2025",
          category: "AI Agent / 可观测性",
          purpose: "智能故障诊断",
          imageSrc: "/cases/sre-copilot.png",
          imageAlt: "智能 SRE 运维助手界面截图，展示 Kubernetes 调查时间线、日志与支持证据",
          imageWidth: 1859,
          imageHeight: 903,
          imageNote: "已授权项目界面截图",
          title: "智能 SRE 运维助手",
          summary:
            "围绕指标、日志和集群事件组织故障排查，让 Agent 的结论建立在可检查的系统证据之上。",
          flow: ["OBSERVE", "REASON", "ACT", "REPORT"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "问题输入 → 调查计划 → 工具作用域校验 → 指标、日志与 Kubernetes 查询 → 流式证据 → 诊断总结。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "明确集群、命名空间与时间窗口边界，将计划和工具调用保存为可观察事件，并支持中断、执行上限与模型降级。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "Spring Boot 3 / React / AI Agent / MCP / Prometheus / Kubernetes",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者；客户敏感信息与量化结果仅在获得授权后披露。",
          tagsLabel: "SRE 助手项目技术标签",
          tags: ["AI AGENT", "MCP", "PROMETHEUS", "KUBERNETES"],
        },
        {
          id: "content-orchestration",
          number: "CASE 04",
          year: "2025—2026",
          category: "AIGC 基础设施 / 任务编排",
          purpose: "批量内容生成调度",
          imageSrc: "/cases/content-orchestration-schematic.png",
          imageAlt: "生成式内容调度平台的任务接入、优先级队列、模型网关与实时进度链路示意图，非实机截图",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "本站调度链路示意图 · 非实机截图",
          title: "生成式内容调度平台",
          summary:
            "面向批量内容生成任务的统一工作台，处理数据导入、模型调度、失败恢复和实时进度。",
          flow: ["IMPORT", "QUEUE", "MODEL", "EXPORT"],
          facts: [
            {
              id: "flow",
              label: "系统链路",
              value:
                "表格导入 → 模板变量与任务校验 → 分级队列 → 多模型网关 → 重试与状态流转 → WebSocket 进度 → 结果导出。",
            },
            {
              id: "focus",
              label: "工程重点",
              value:
                "统一输入校验和任务标准，管理优先级、队列积压与失败重试，隔离模型供应方差异并实时反馈进度。",
            },
            {
              id: "stack",
              label: "技术栈",
              value: "NestJS / TypeScript / Redis Stream / WebSocket / Vue 3 / Docker",
            },
          ],
          role: "项目主导者",
          roleNote: "风雨确认担任项目主导者；客户敏感信息与量化结果仅在获得授权后披露。",
          tagsLabel: "生成式内容调度项目技术标签",
          tags: ["TASK QUEUE", "MODEL GATEWAY", "WEBSOCKET", "DOCKER"],
        },
      ],
    },
    process: {
      label: "PROCESS",
      labelLocal: "合作流程",
      kicker: "DISCOVER. PROTOTYPE. DEPLOY. ITERATE.",
      title: ["一条从现场问题到", "生产结果的闭环。"],
      steps: [
        { id: "discover", number: "01", tag: "DISCOVER", title: "深入现场，定义问题", description: "对齐业务目标、用户流程、数据条件与成功标准。" },
        { id: "prototype", number: "02", tag: "PROTOTYPE", title: "快速构建，真实验证", description: "用可工作的原型验证关键假设，尽早暴露风险。" },
        { id: "deploy", number: "03", tag: "DEPLOY", title: "接入系统，稳定上线", description: "完成产品化、系统集成、测试发布与运行保障。" },
        { id: "iterate", number: "04", tag: "ITERATE", title: "观察使用，持续迭代", description: "根据业务结果和真实反馈优化流程、体验与模型。" },
      ],
    },
    about: {
      label: "PHILOSOPHY",
      labelLocal: "我的理念",
      quote: "“FDE 的价值，不是带着标准答案，而是和团队一起把答案跑通。”",
      body: "我相信 AI 落地是一项跨越业务、产品和工程的协作工作。好的方案既要理解人的需求与组织现实，也要经得起数据、权限、稳定性和长期维护的检验。",
    },
    contact: {
      label: "CONTACT",
      labelLocal: "开始合作",
      status: "开放沟通中",
      titleStart: "有一个 AI 场景，",
      titleEnd: "需要真正落地？",
      body: "无论是尚未验证的 AI 机会，还是卡在原型、集成或上线阶段的项目，都可以先聊聊。直接发邮件，或先复制一份简洁的合作沟通模板。",
      emailListLabel: "联系邮箱",
      emailAria: "发送合作邮件到",
      copyIdle: "复制合作沟通模板",
      copyWorking: "正在复制合作模板",
      copyDone: "合作模板已复制",
      copyFailed: "复制失败，请重试",
      copyCodeIdle: "COPY BRIEF",
      copyCodeWorking: "COPYING",
      copyCodeDone: "COPIED",
      copyCodeFailed: "RETRY",
      liveDone: "合作沟通模板已复制到剪贴板",
      liveFailed: "复制失败，请重试",
      mailSubject: "FDE / AI 落地项目合作咨询",
      mailTemplate: `你好风雨，我想沟通一个 FDE / AI 落地项目。\n\n业务场景：\n当前问题：\n期望结果：\n计划时间：`,
    },
    footer: {
      tagline: "把 AI 部署进真实业务现场。",
      backToTop: "返回顶部 ↑",
    },
  },
  en: {
    seo: {
      title: "Fengyu — Forward Deployed Engineer",
      description:
        "From field discovery and AI prototyping to system integration and production deployment, I help teams turn AI opportunities into working outcomes.",
    },
    preferences: {
      group: "Language and theme settings",
      switchToEnglish: "Switch to English",
      switchToChinese: "切换为中文",
      switchToLight: "Switch to light mode",
      switchToDark: "Switch to dark mode",
      changedToEnglish: "Language changed to English",
      changedToChinese: "语言已切换为中文",
    },
    header: {
      home: "Fengyu home",
      availability: "Available for FDE engagements",
      navLabel: "Primary navigation",
      services: "Services",
      partners: "Partners",
      caseStudy: "Work",
      process: "Process",
      about: "About",
      contact: "Start a project",
      contactShort: "Talk",
    },
    hero: {
      index: "DISCOVER / PROTOTYPE / DEPLOY / ITERATE — 2026",
      kicker: "FORWARD DEPLOYED ENGINEER / FIELD TO PRODUCTION",
      kickerAside: "AI SOLUTIONS / PRODUCT / DELIVERY",
      title: [
        { text: "Enter the workflow,", outlined: false },
        { text: "turn AI into", outlined: true },
        { text: "a working outcome.", outlined: false },
      ],
      label: "00 / INTRODUCTION",
      intro:
        "I’m Fengyu, a Forward Deployed Engineer. I work alongside business teams—from problem framing and prototype validation to production integration—to close the last mile of AI delivery.",
      cta: "See how I work",
      scroll: "Scroll to explore",
    },
    ticker: {
      aria: "Core capabilities",
      items: ["Field discovery", "AI prototypes", "System integration", "Production delivery", "Continuous iteration"],
    },
    servicesSection: {
      label: "SERVICES",
      labelLocal: "What I deliver",
      kicker: "FROM FIELD TO PRODUCTION",
      title: ["Start with the real workflow,", "then put AI into production."],
    },
    services: [
      {
        id: "discovery",
        number: "01",
        tag: "DISCOVERY & STRATEGY",
        title: "Business discovery & solution design",
        description: "Work inside the real operating context to clarify goals, workflows and constraints, then identify the AI opportunity worth pursuing.",
        items: ["Workflow and pain-point interviews", "AI opportunity and risk mapping", "Solution architecture and value definition"],
      },
      {
        id: "prototype",
        number: "02",
        tag: "PROTOTYPE & VALIDATE",
        title: "AI prototypes & agent validation",
        description: "Build a usable prototype quickly and validate it against real data and user feedback—not a polished concept demo.",
        items: ["Workflow and agent prototypes", "Tool use and data integration", "Evaluation and safety boundaries"],
      },
      {
        id: "delivery",
        number: "03",
        tag: "INTEGRATE & DEPLOY",
        title: "Production integration & delivery",
        description: "Connect validated solutions to existing systems, data and permissions, then carry them across the last mile into production.",
        items: ["Full-stack product engineering", "Enterprise systems and model integration", "Testing, release and observability"],
      },
      {
        id: "iteration",
        number: "04",
        tag: "ADOPT & ITERATE",
        title: "Adoption & continuous iteration",
        description: "Improve the experience, workflow and model around real usage so the solution is adopted and keeps creating value.",
        items: ["Usage feedback and outcome review", "Workflow and model optimization", "Capability transfer and handoff"],
      },
    ],
    serviceAria: "Learn about and discuss",
    capabilitiesSection: {
      label: "CAPABILITIES",
      labelLocal: "How I contribute",
      title: ["Close to the field.", "Strong in engineering.", "Ready for production."],
      intro: "An FDE connects customers, operations, product and engineering. I turn uncertain AI opportunities into testable prototypes, then reliable systems.",
    },
    capabilities: [
      { id: "field", number: "01", title: "Field collaboration", description: "Work beside frontline users and business owners to turn vague needs into testable problems." },
      { id: "prototype", number: "02", title: "Rapid AI prototyping", description: "Combine models, tools and data into workflows people can experience and evaluate." },
      { id: "integration", number: "03", title: "Full-stack integration", description: "Connect frontend, backend, enterprise systems and AI capabilities across the critical path." },
      { id: "production", number: "04", title: "Production delivery", description: "Cover permissions, evaluation, logs, release and iteration so the solution runs reliably." },
    ],
    partners: {
      label: "TRUST & COLLABORATION",
      labelLocal: "Selected partners",
      kicker: "DISCLOSED WITH PERMISSION",
      title: ["Real collaboration.", "Only disclosed with permission."],
      intro: "The public wall currently lists the WUDE project team, whose participation has been confirmed. Company names and logos are added only with permission—never invented to inflate a track record.",
      aria: "Disclosed partners and projects",
      tiles: [
        { id: "wude", kind: "brand", eyebrow: "CONFIRMED PARTICIPATION", mark: "WUDE", name: "WUDE project team", note: "Engineering portfolio and technical content site" },
        { id: "disclosure", kind: "policy", eyebrow: "DISCLOSURE POLICY", mark: "WITH PERMISSION", name: "Real company names and logos", note: "Client information appears only when approved" },
        { id: "next", kind: "cta", eyebrow: "NEXT COLLABORATION", mark: "YOUR TEAM", name: "Become the next public case", note: "Start with one real business problem" },
      ],
    },
    caseStudy: {
      label: "PARTICIPATED WORK",
      labelLocal: "System cases",
      kicker: "AI APPLICATIONS / PLATFORM ENGINEERING",
      title: ["Four real system cases,", "documented directly on this site."],
      intro:
        "From user-facing services to knowledge retrieval, intelligent operations and content orchestration, each case presents the system context, engineering flow and technology choices directly on this page.",
      previous: "Previous case",
      next: "Next case",
      keyboardHint: "Focus the case and use Left or Right Arrow to switch; Home and End jump to the first or last case.",
      imageLabel: "PROJECT MATERIAL",
      roleLabel: "MY ROLE",
      discuss: "Discuss a similar project",
      disclosure:
        "These are team projects led by Fengyu. This site presents only publicly verifiable system information; team, client-sensitive details and measured outcomes are disclosed only with permission.",
      projects: [
        {
          id: "mental-health-platform",
          number: "CASE 01",
          year: "2026",
          category: "Industry SaaS / AI Application",
          purpose: "AI mental health services",
          imageSrc: "/cases/mental-health-platform.png",
          imageAlt: "Dabai AI mental health platform project visual showing AI consultation, organizational wellbeing profiles, risk alerts and rapid screening",
          imageWidth: 903,
          imageHeight: 502,
          imageNote: "Authorized project promotional visual",
          title: "Dabai AI Mental Health Platform",
          summary:
            "An AI-enabled mental health product combining consultation, psychological profiling, risk alerts and rapid screening for individual and organizational use.",
          flow: ["ASSESS", "CHAT", "SERVICE", "DELIVER"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Service discovery and gateway → user and session state → SSE-based AI conversations → assessments and reports → consultation, transaction and payment → continuous delivery.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Traceable state across conversations, assessments, consultations and transactions, with asynchronous callbacks, timeout handling, payment idempotency, release checks and rollback readiness.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Spring Cloud / SSE / MongoDB / Payment / Vue 3 / CI/CD",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead; client-sensitive details and measured outcomes are disclosed only with permission.",
          tagsLabel: "Dabai AI project technology tags",
          tags: ["AI CONSULTATION", "SSE", "TRANSACTION STATE", "CI/CD"],
        },
        {
          id: "industrial-compliance-platform",
          number: "CASE 02",
          year: "2025–2026",
          category: "Private AI / RAG Platform",
          purpose: "Enterprise compliance retrieval",
          imageSrc: "/cases/industrial-compliance-platform.png",
          imageAlt: "Industrial compliance knowledge platform interface showing regional risk trends, a risk heat map and radar chart",
          imageWidth: 1859,
          imageHeight: 912,
          imageNote: "Authorized project interface capture",
          title: "Industrial Compliance Knowledge Platform",
          summary:
            "A private knowledge platform that turns internal compliance documents into searchable, traceable and rebuildable knowledge.",
          flow: ["DOCS", "PARSE", "INDEX", "ANSWER"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Document ingestion → parsing, cleaning and chunking → asynchronous embedding → hybrid retrieval and reranking → local-model generation → source traceability.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Re-runnable document pipelines, recoverable asynchronous embedding tasks, private model deployment, graceful degradation and source-backed answers.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Java 17 / RAG / Redis Stream / Vector Search / Local LLM / Kubernetes",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead; client-sensitive details and measured outcomes are disclosed only with permission.",
          tagsLabel: "Industrial compliance project technology tags",
          tags: ["PRIVATE AI", "HYBRID SEARCH", "LOCAL LLM", "KUBERNETES"],
        },
        {
          id: "sre-copilot",
          number: "CASE 03",
          year: "2025",
          category: "AI Agent / Observability",
          purpose: "Intelligent incident diagnosis",
          imageSrc: "/cases/sre-copilot.png",
          imageAlt: "Intelligent SRE operations assistant interface showing a Kubernetes investigation timeline, logs and supporting evidence",
          imageWidth: 1859,
          imageHeight: 903,
          imageNote: "Authorized project interface capture",
          title: "Intelligent SRE Operations Assistant",
          summary:
            "An operations assistant that organizes incident investigation around metrics, logs and cluster events, grounding its conclusions in inspectable evidence.",
          flow: ["OBSERVE", "REASON", "ACT", "REPORT"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "User question → investigation plan → tool-scope validation → metrics, logs and Kubernetes queries → streamed evidence → diagnostic summary.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Explicit cluster, namespace and time-window boundaries, observable tool events, interruption, execution limits and model fallback.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "Spring Boot 3 / React / AI Agent / MCP / Prometheus / Kubernetes",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead; client-sensitive details and measured outcomes are disclosed only with permission.",
          tagsLabel: "SRE assistant project technology tags",
          tags: ["AI AGENT", "MCP", "PROMETHEUS", "KUBERNETES"],
        },
        {
          id: "content-orchestration",
          number: "CASE 04",
          year: "2025–2026",
          category: "AIGC Infrastructure / Orchestration",
          purpose: "Batch content generation orchestration",
          imageSrc: "/cases/content-orchestration-schematic.png",
          imageAlt: "Non-production schematic of task intake, priority queues, a model gateway and live progress for the generative content orchestration platform",
          imageWidth: 1600,
          imageHeight: 900,
          imageNote: "On-site orchestration schematic · not a production screenshot",
          title: "Generative Content Orchestration Platform",
          summary:
            "A unified workspace for batch content generation, covering data ingestion, model orchestration, failure recovery and live progress.",
          flow: ["IMPORT", "QUEUE", "MODEL", "EXPORT"],
          facts: [
            {
              id: "flow",
              label: "System flow",
              value:
                "Spreadsheet import → template variables and validation → priority queues → multi-model gateway → retries and state transitions → WebSocket progress → export.",
            },
            {
              id: "focus",
              label: "Engineering focus",
              value:
                "Standardized validation and task definitions, queue pressure and retry management, provider abstraction and real-time execution feedback.",
            },
            {
              id: "stack",
              label: "Technology",
              value: "NestJS / TypeScript / Redis Stream / WebSocket / Vue 3 / Docker",
            },
          ],
          role: "Project lead",
          roleNote: "Fengyu confirms serving as project lead; client-sensitive details and measured outcomes are disclosed only with permission.",
          tagsLabel: "Generative content orchestration technology tags",
          tags: ["TASK QUEUE", "MODEL GATEWAY", "WEBSOCKET", "DOCKER"],
        },
      ],
    },
    process: {
      label: "PROCESS",
      labelLocal: "How we work",
      kicker: "DISCOVER. PROTOTYPE. DEPLOY. ITERATE.",
      title: ["One loop from a field problem", "to a production outcome."],
      steps: [
        { id: "discover", number: "01", tag: "DISCOVER", title: "Enter the field, define the problem", description: "Align on business goals, user workflows, data conditions and success criteria." },
        { id: "prototype", number: "02", tag: "PROTOTYPE", title: "Build quickly, validate for real", description: "Use a working prototype to test critical assumptions and expose risk early." },
        { id: "deploy", number: "03", tag: "DEPLOY", title: "Integrate, harden and launch", description: "Complete productization, system integration, testing, release and operational readiness." },
        { id: "iterate", number: "04", tag: "ITERATE", title: "Observe usage, keep improving", description: "Improve the workflow, experience and model using business outcomes and real feedback." },
      ],
    },
    about: {
      label: "PHILOSOPHY",
      labelLocal: "What I believe",
      quote: "“An FDE does not arrive with a standard answer. The job is to help the team make the answer work.”",
      body: "AI delivery is a collaboration across business, product and engineering. A strong solution understands people and organizational reality—and stands up to data, permissions, reliability and long-term maintenance.",
    },
    contact: {
      label: "CONTACT",
      labelLocal: "Start a project",
      status: "Open for conversation",
      titleStart: "Have an AI use case",
      titleEnd: "that needs to work?",
      body: "Whether you are exploring an unvalidated AI opportunity or a project stuck at prototype, integration or launch, we can start with a focused conversation. Email me directly or copy the short project brief.",
      emailListLabel: "Contact email addresses",
      emailAria: "Send a project email to",
      copyIdle: "Copy the project brief",
      copyWorking: "Copying the project brief",
      copyDone: "Project brief copied",
      copyFailed: "Copy failed. Try again",
      copyCodeIdle: "COPY BRIEF",
      copyCodeWorking: "COPYING",
      copyCodeDone: "COPIED",
      copyCodeFailed: "RETRY",
      liveDone: "The project brief was copied to your clipboard",
      liveFailed: "Copy failed. Please try again",
      mailSubject: "FDE / AI delivery project inquiry",
      mailTemplate: `Hi Fengyu, I’d like to discuss an FDE / AI delivery project.\n\nBusiness context:\nCurrent problem:\nDesired outcome:\nTarget timeline:`,
    },
    footer: {
      tagline: "Deploy AI into real operating workflows.",
      backToTop: "BACK TO TOP ↑",
    },
  },
} as const;
